### PR TITLE
Updated to support rails 5.0

### PR DESCRIPTION
**Pull request by rfestag**
I am playing with newer versions of some libraries that require activesupport 5.x. I updated the versions, and all tests passed on my end.

### CODE REVIEW

**Comment by rgarner** [comment]
Thanks!

**Comment by rfestag** [comment]
No problem. Any chance of publishing an updated gem with this?

**Comment by rgarner** [comment]
Yes. But not today ;)

**Comment by rfestag** [comment]
Hah, no worries, sounds good. Thanks!

**Pull request merged**
